# Generated by Django 5.1.2 on 2024-10-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('booking_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('phone', models.CharField()),
                ('symptoms', models.CharField()),
                ('date_now', models.DateField(auto_now_add=True)),
                ('date_reserve', models.DateField()),
                ('time_reserve', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connects.location')),
            ],
        ),
    ]
