# Generated by Django 3.2.25 on 2026-04-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('maintenance', 'Maintenance')], default='open', max_length=20),
        ),
    ]
