# Generated by Django 5.1.2 on 2024-10-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connects', '0003_remove_booking_date_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='booker',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
    ]
