# Generated by Django 3.2.25 on 2026-05-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connects', '0002_alter_location_status'),
        ('connects', '0004_rename_first_name_booking_booker_and_more'),
    ]

    operations = [
    ]
