version: '3'

services:
  web:
    build: .
    command: python3 wellcare/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - cloudsql-proxy
    environment:
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    command: /cloud_sql_proxy -instances=geometric-team-431707-c2:asia-southeast1:wellcare=tcp:5432
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/cloudsql/credentials.json
    volumes:
      - ./credentials:/secrets/cloudsql
    ports:
      - "5432:5432"
